### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by ewrfcas** [Yannnnnnnnnnnn/DispMVS_release#1]
Hi, thanks for your great work.
It is really interesting to learn a depth range free MVS model.
I know the fact that flow/E-flow/depth can be converted to each other.
But after reading the paper, I still have two questions. 

1) How to sample for the E-flow after the initialization or stage changing? I cannot understand the sampling details from the E-flow Estimation of Sec3.3, especially for the random initialization. Besides, Eq(12), what does "D" mean? And how to understand Eq(12) while "i" emerge on both sides of the equation.

2) The paper claims that DispMVS builds a 2D cost volume. But why just "2D cost volume" is enough? Even with the epipolar constraint, we still need HxWxD to calculate the similarity along the epipolar lines for each point in the reference view. Eq(12) also shows the summation along the epipolar line (maybe) ?

Looking forward to the code release may well answer my confusion.

**Comment by yanqswhu** [comment]
I am sorry for the late response.

1. The D is the number of the channel of the extracted feature from the encoder. I am sorry that I did not make it clear in the paper, and you can check the code for more details.

2. As far as I know, the tensor with the shape HxWxD is a 2d cost volume, and the tensor with the shape HxWxDxS is a 3D cost volume. I agree it is confusing, but most people in this area follow this rule.


Thanks again for your attention. I have released my code, and please contact me if you have other questions.

**Comment by ewrfcas** [comment]
Thanks for your response. I have misundertood sth, which is corrected after reading the code.
